# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUIManager', '0002_auto_20180417_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='journal_name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
