# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUIManager', '0003_auto_20180418_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='is_ready',
            field=models.BooleanField(default=True),
        ),
    ]
