# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GUIManager', '0004_algorithm_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrecommendations',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemrecommendations',
            name='modified_on',
            field=models.DateField(auto_now=True),
        ),
    ]
