# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUIManager', '0005_auto_20180426_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemrecommendations',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='systemrecommendations',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
