# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GUIManager', '0006_auto_20180426_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlgorithmRecommendationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GUIManager.Recommendation')),
                ('system_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUIManager.SystemRecommendations')),
            ],
        ),
    ]
